# -----------------------------
# PostgreSQL Datasource
# -----------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/hospitalmanagementdb
spring.datasource.username=user
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# -----------------------------
# Hibernate / JPA
# -----------------------------
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql
